name: flutter_proofapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_preview: ^1.1.0
  screenshot_modes: ^1.0.0
  path: ^1.8.2
  google_fonts: ^3.0.1
  material_color_utilities: ^0.1.5
  flex_color_scheme: ^5.1.0
  # intl gen
  intl: ^0.17.0
  intl_utils: ^2.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.17.0


  lint: ^1.8.2


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - google_fonts/
# flutter intl for localization settings
flutter_intl:
  enabled: true   
  class_name: S   
  main_locale: en 
  arb_dir: lib/src/localization
  output_dir: lib/src/localization_gen
  use_deferred_loading: false
  

